<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>037AC246-398C-4216-BB3A-9324FA8E9F40</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.ApplicationInsights" />
    <PackageReference Include="Aspire.Hosting.Azure.AppService" />
    <PackageReference Include="Aspire.Hosting.Azure.Sql" />
    <!-- TODO: Remove when Aspire updates StreamJsonRpc's MessagePack dependency to fix https://github.com/advisories/GHSA-hv8m-jj95-wg3x -->
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WebApi\WebApi.csproj" />
    <ProjectReference Include="..\MigrationService\MigrationService.csproj" />
  </ItemGroup>

</Project>
