@baseUrl = https://localhost:7255/api
# Dan's A Team
#@teamId = 586d22ef-8bd7-4db0-826a-bfdabfb1742e

# Marvel
@teamId = 1dd5d1f1-764f-4e9c-95dd-141acf8c2ec7

@heroId = 502b268c-1bcf-4ebd-a5e1-00a1967c87f2

### GET Heroes
GET {{baseUrl}}/heroes

### GET Teams
GET {{baseUrl}}/teams

### Add Hero to Team
POST {{baseUrl}}/teams/{{teamId}}/heroes/{{heroId}}

### Get Team
GET {{baseUrl}}/teams/{{teamId}}

### Create Team
POST {{baseUrl}}/teams
Content-Type: application/json

{
    "name": "Dans A-Team"
}
